title: bas-community-wiki
lang: en
description: Blade and Sorcery Community Wiki
repository: Wully616/bas-community-wiki
remote_theme: Wully616/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions